# Generated by Django 3.2.13 on 2023-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myimage')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('description', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=20)),
                ('e_email', models.EmailField(max_length=30)),
                ('picture', models.ImageField(upload_to='images')),
                ('college', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('mode', models.CharField(max_length=30)),
            ],
        ),
    ]
