# Generated by Django 3.2.13 on 2023-02-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('hostel', models.CharField(max_length=50)),
                ('room_no', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
