# Generated by Django 3.2.13 on 2023-02-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='details',
        ),
    ]
