# Generated by Django 3.2.13 on 2023-02-04 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_delete_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='detail',
            new_name='Details',
        ),
    ]
