# Generated by Django 3.2.13 on 2023-02-04 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_rename_detail_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Deta',
        ),
    ]
