# Generated by Django 3.2.13 on 2023-02-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_rename_details_deta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_warden', models.CharField(max_length=30)),
                ('hostel_name', models.CharField(max_length=30)),
                ('wanden_email', models.EmailField(max_length=30)),
                ('tstudent', models.CharField(max_length=100)),
                ('troom', models.CharField(max_length=50)),
                ('tfloor', models.CharField(max_length=10)),
            ],
        ),
    ]
