# Generated by Django 3.2.13 on 2023-02-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_mess_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess_timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=30)),
                ('sunday_breakfast', models.CharField(max_length=30)),
                ('sunday_lunch', models.CharField(max_length=30)),
                ('sunday_snack', models.CharField(max_length=30)),
                ('sunday_dinner', models.CharField(max_length=30)),
                ('monday_breakfast', models.EmailField(max_length=30)),
                ('monday_lunch', models.EmailField(max_length=30)),
                ('monday_snack', models.EmailField(max_length=30)),
                ('monday_dinner', models.EmailField(max_length=30)),
                ('tuesday_breakfast', models.CharField(max_length=100)),
                ('tuesday_lunch', models.CharField(max_length=100)),
                ('tuesday_snack', models.CharField(max_length=100)),
                ('tuesday_dinner', models.CharField(max_length=100)),
                ('wednesday_breakfast', models.CharField(max_length=50)),
                ('wednesday_lunch', models.CharField(max_length=50)),
                ('wednesday_snack', models.CharField(max_length=50)),
                ('wednesday_dinner', models.CharField(max_length=50)),
                ('thursday_breakfast', models.CharField(max_length=50)),
                ('thursday_lunch', models.CharField(max_length=50)),
                ('thursday_snack', models.CharField(max_length=50)),
                ('thursday_dinner', models.CharField(max_length=50)),
                ('friday_breakfast', models.CharField(max_length=10)),
                ('friday_lunch', models.CharField(max_length=10)),
                ('friday_snack', models.CharField(max_length=10)),
                ('friday_dinner', models.CharField(max_length=10)),
                ('sarturday_breakfast', models.CharField(max_length=10)),
                ('sarturday_lunch', models.CharField(max_length=10)),
                ('sarturday_snack', models.CharField(max_length=10)),
                ('sarturday_dinner', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Mess_schedule',
        ),
    ]
