# Generated by Django 3.2.13 on 2023-02-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_auto_20230204_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess_timetable',
            name='contact_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mess_timetable',
            name='secretary_name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
