# Generated by Django 3.2.13 on 2023-02-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0014_auto_20230204_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess_timetable',
            name='contact_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='friday_breakfast',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='friday_dinner',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='friday_lunch',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='friday_snack',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='monday_breakfast',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='monday_dinner',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='monday_lunch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='monday_snack',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='sarturday_breakfast',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='sarturday_dinner',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='sarturday_lunch',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='mess_timetable',
            name='sarturday_snack',
            field=models.CharField(max_length=40),
        ),
    ]
