# Generated by Django 3.2.13 on 2023-02-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_auto_20230204_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('room_no', models.CharField(max_length=5)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
