# Generated by Django 3.2.13 on 2023-02-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_auto_20230205_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='hostel',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
